eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761,http://localhost:8762,http://localhost:8763}/eureka/
    instance:
      hostname: ${INSTANCE_ID:unknown}
      leaseRenewalIntervalInSeconds: 15
      leaseExpirationDurationInSeconds: 30
      preferIpAddress: true
