eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_PEER:http://localhost:8761/eureka/}
    instance:
      hostname: ${INSTANCE_ID:unknown}
      leaseRenewalIntervalInSeconds: 3
