eureka:
  client:
    # healthcheck:
    #   enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      # hostname: test.bracbank.com
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:${spring.cloud.nacos.config.group}
      prefer-ip-address: true
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 15
