eureka:
  client:
    # healthcheck:
    #   enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      # hostname: ${INSTANCE_ID:unknown}
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 15
      preferIpAddress: true
