eureka:
  client:
    # healthcheck:
    #   enabled: true
    register-with-eureka: true
    fetch-registry: true
    # service-url:
    #   defaultZone: http://localhost:8761/eureka
    prefer-same-zone-eureka: true
    region: region-1
    service-url:
      zone1: http://my-eureka-server-1.com:8761/eureka/
      zone2: http://my-eureka-server-2.com:8762/eureka/
      zone3: http://my-eureka-server-3.com:8763/eureka/
    availability-zones:
      region-1: zone1,zone2,zone3
    instance:
      hostname: localhost
      # instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:${spring.cloud.nacos.config.group}
      prefer-ip-address: false
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 15
